baseURL = 'https://3d-manipulation-workshop.github.io/'
languageCode = 'en-us'
title = '3DVRM Workshop @ ICRA 2024'
theme = 'console'


[[params.navlinks]]
  name = "home/"
  url = "/"
  
  [[params.navlinks]]
  name = "call for papers/"
  url = "call/"